export const plans = [
    {
        name: "Free",
        description: "Perfect for side projects and learning",
        price: "0 zł",
        interval: "forever",
        features: [
            "Up to 3 projects",
            "1GB storage",
            "Basic analytics",
            "Community support",
        ],
        authPlanName: "free",
        popular: false,
    },
    {
        name: "Pro",
        description: "For professional developers and small teams",
        price: "20 zł",
        interval: "month",
        features: [
            "Unlimited projects",
            "10GB storage",
            "Advanced analytics",
            "Priority support",
            "Custom domains",
            "Team collaboration",
        ],
        authPlanName: "pro",
        popular: true,
    },
    {
        name: "Pro+",
        description: "For large teams and organizations",
        price: "30 zł",
        interval: "month",
        features: [
            "Everything in Pro",
            "Unlimited storage",
            "Custom analytics",
            "Dedicated support",
            "SLA guarantee",
            "Custom integrations",
            "Advanced security",
        ],
        authPlanName: "pro+",
        popular: false,
    },
];
